import NavBar from "@/components/organisms/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { footerLinks, legalLinks, navPrimary, navSecondary } from "@/constants";
import { GoFundMe } from "@/components/atoms/Logos/Logos";
import Providers from "@/constants/provider";
import ThemeButton from "@/components/utilities/ThemeButton";
import Footer from "../components/organisms/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="light"
      style={{
        colorScheme: "light",
      }}
    >
      <body>
        <Providers>
          <NavBar
            headerAnimation={true}
            navPrimary={navPrimary}
            navSecondary={navSecondary}
            logo={<GoFundMe />}
          />

          {children}

          <ThemeButton />
          <Footer
            footerLinks={footerLinks}
            legalLinks={legalLinks}
            logo={<GoFundMe />}
          />
        </Providers>
      </body>
    </html>
  );
}
