import NavBar from "@/components/organisms/Header/Header"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { navPrimary, navSecondary } from "@/constants"
import { GoFundMe } from "@/components/atoms/Logos/Logos"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NavBar
          navPrimary={navPrimary}
          navSecondary={navSecondary}
          logo={<GoFundMe />}
        />
        {children}
      </body>
    </html>
  )
}
